accounts/urls.py
#  file: accounts/urls.py

from django.urls import path

from accounts.views import (KakaoLogoutView, KakaoCallBackView, KakaoView, UserListListAPIView, 
          UserListRetrieveAPIView, UserInterestListAPIView, UserPortfolioListAPIView)
from accounts.views import UserInformationView
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView, TokenVerifyView
)

app_name = 'accounts'

urlpatterns = [
    path('userlist/', UserListListAPIView.as_view(), name='userlist-list'),
    path('userlist/<int:id_user>/',
         UserListRetrieveAPIView.as_view(), name='userlist-detail'),

    path('userinterest/', UserInterestListAPIView.as_view(),
         name='userinterest-list'),
    path('userportfolio/', UserPortfolioListAPIView.as_view(),
         name='userportfolio-list'),

    path('userinformation/<int:id_user>/', 
          UserInformationView.as_view(), name='userinformation-detail'), 


    # https://velog.io/@junsikchoi/Django%EB%A1%9C-%EC%B9%B4%EC%B9%B4%EC%98%A4-%EC%86%8C%EC%85%9C-%EB%A1%9C%EA%B7%B8%EC%9D%B8%EC%9D%84-%ED%95%B4%EB%B3%B4%EC%9E%90
    path('kakao/login/', KakaoView.as_view(), name='kakao-login'),
    path('kakao/callback/', KakaoCallBackView.as_view()),
    path('kakao/logout/', KakaoLogoutView.as_view(), name='kakao-logout'),

    
    # (11/1) simple-jwt 구현 
    path('jwt/', TokenObtainPairView.as_view(), name='token-obtain-pair'),
    path('jwt/refresh/', TokenRefreshView.as_view(), name='token-refresh'),
    path('jwt/verify/', TokenVerifyView.as_view(), name='token-verify'),
]

api/urls.py
#  file: api/urls.py
from django.urls import path, register_converter
from api.converters import DateConverter

from api.views import StockListListAPIView, StockListRetrieveAPIView
from api.views import StockInformationHistoryListAPIView, StockInformationHistoryRetrieveAPIView, StockInformationSparkListAPIView
from api.views import StockPriceHistoryListAPIView, StockPriceHistoryRetrieveAPIView, StockPriceSparkListAPIView
from api.views import HistoricalStockPriceAPIView, StockSummaryAPIView, StockYearlyFinancialStatementsAPIView, StockQuarterlyFinancialStatementsAPIView, StockProfileAPIView


app_name = 'api'
register_converter(DateConverter, 'date')

urlpatterns = [
    path('stocklist/', StockListListAPIView.as_view(), name='stocklist-list'),
    path('stocklist/<str:ticker>/',
         StockListRetrieveAPIView.as_view(), name='stocklist-detail'),

    path('stockinformationhistory/<str:ticker>/',
         StockInformationHistoryListAPIView.as_view(), name='stockinformationhistory-list'),
    path('stockinformationhistory/<str:ticker>/<date:update_date>/',
         StockInformationHistoryRetrieveAPIView.as_view(), name='stockinformationhistory-detail'),
    path('stockinformationspark/<str:ticker>/<date:s_date>-<date:e_date>/',
         StockInformationSparkListAPIView.as_view(), name='stockinformationspark-list'),

    path('stockpricehistory/<str:ticker>/',
         StockPriceHistoryListAPIView.as_view(), name='stockpricehistory-list'),
    path('stockpricehistory/<str:ticker>/<date:update_date>/',
         StockPriceHistoryRetrieveAPIView.as_view(), name='stockpricehistory-detail'),
    path('stockpricespark/<str:ticker>/<date:s_date>-<date:e_date>/',
         StockPriceSparkListAPIView.as_view(), name='stockpricespark-list'),
    
    path('historicalstockprice/<str:ticker>/<date:s_date>-<date:e_date>/', 
          HistoricalStockPriceAPIView.as_view(), name='historicalstockprice-list'),
    path('stocksummary/<str:ticker>/', 
          StockSummaryAPIView.as_view(), name='stocksummary-detail'),
    path('stockyearlyfinancialstatements/<str:ticker>/',  
          StockYearlyFinancialStatementsAPIView.as_view(), name='stockyearlyfinancialstatements-detail'),
    path('stockquarterlyfinancialstatements/<str:ticker>/',  
          StockQuarterlyFinancialStatementsAPIView.as_view(), name='stockquarterlyfinancialstatements-detail'),
    path('stockprofile/<str:ticker>/',  
          StockProfileAPIView.as_view(), name='stockprofile-detail'), 
]

backend/urls.py
#  file: backend/urls.py

"""backend URL Configuration
The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include, re_path
from backend.views import HomeView

from rest_framework.permissions import AllowAny
from drf_yasg.views import get_schema_view 
from drf_yasg import openapi

schema_url_patterns = [ 
    path('api/', include('api.urls')), 
    path('accounts/', include('accounts.urls')), 
    
    ]

schema_view_v1 = get_schema_view(
    openapi.Info(
        title="ORUUM API",
        default_version='v1',
        description="ORUUM API Document",
        terms_of_service="https://www.google.com/policies/terms/",
    ),
    public=True,
    permission_classes=(AllowAny,),
    patterns=schema_url_patterns,
)

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),

    path('accounts/', include('accounts.urls')),
    # oauth를 위한 url
    # path('accounts/', include('allauth.urls')),
    
    # dashboard를 위한 url
    path('dashboard/', include('dashboard.urls')),
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
    
    # re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view_v1.without_ui(cache_timeout=0), name='schema-json'),
    # re_path(r'^swagger/$', schema_view_v1.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^docs/$', schema_view_v1.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ORUUM</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

</head>

<body>
    {% load socialaccount %}
    {% load static %}
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">ORUUM</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="admin/">Admin</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Account
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'accounts:userlist-list' %}">list</a></li>
                            <li><a class="dropdown-item" href="{% url 'accounts:userinterest-list' %}">interest</a></li>
                            <li><a class="dropdown-item" href="{% url 'accounts:userportfolio-list' %}">portfolio</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Stock
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="api/stocklist/">list</a></li>
                            <li><a class="dropdown-item" href="api/stockpricehistory/AAPL/">price</a></li>
                            <li><a class="dropdown-item" href="api/stockinformationhistory/AAPL/">information</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Dashboard
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="dashboard/line/AAPL/">line</a></li>
                            <li><a class="dropdown-item" href="dashboard/bar/NASDAQ/">bar</a></li>
                            <li><a class="dropdown-item" href="dashboard/dash/">dash</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Docs
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="docs/">Docs</a></li>
                            <!-- <li><a class="dropdown-item" href="swagger/">swaDocs</a></li> -->

                            </ul>
                    </li>
                </ul>
                <a href="/accounts/kakao/login/"><button class="btn"><img class="btn-img" src="{% static 'kakao_login_medium_narrow.png'%}" alt=""></button></a>
            </div>
        </div>
    </nav>

    <p class="text-center fs-2 fw-bold font-monospace">ORUUM-REST-API</p>
    <p class="text-center fs-2 font-monospace" id="Now"></p>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous"></script>
    <script type="text/javascript">
        function getClock() {
            var date = new Date();

            var hours = String(date.getHours()).padStart(2, "0");
            var min = String(date.getMinutes()).padStart(2, "0");
            var sec = String(date.getSeconds()).padStart(2, "0");

            var year = String(date.getFullYear()).substr(2);
            var month = date.getMonth() + 1;
            var day = date.getDate();

            var timeBoard = document.getElementById("Now"); // 값이 입력될 공간
            timeBoard.innerHTML = `${year}. ${month}. ${day}. ${hours} : ${min} : ${sec}`;
            setInterval(getClock, 1000);
        }
    </script>
</body>

</html>

templates/test1_dashplot.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ORUUM</title>
</head>

<body>
    <p>
        <center>TEST-DASH</center>
        {{target_plot|safe}}
    </p>
</body>

</html>

templates/test2_dashplot.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ORUUM</title>
</head>

<body>
    <p>
        <center>TEST-DASH</center>
        {%load plotly_dash%}
        {%plotly_app name="TickerPlot"%}
    </p>

</body>

</html>

templates/test_dashplot.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ORUUM</title>
</head>

<body>
    <p>
        <center>TEST-DASH</center>
        {{target_plot|safe}}
    </p>
</body>

</html>